tablist:
  enabled: true
  update: 1
  header:
    - '&cHEADER'
  footer:
    - '&cFOOTER'
messages:
  join:
    enabled: true
    message: '&e%prefix%%player%%suffix% &ejoined the game'
  leave:
    enabled: true
    message: '&e%prefix%%player%%suffix% &eleft the game'
  chat:
    enabled: true
    message: '&e%prefix%%player%%suffix%&r: %message%'
pm_tcom:
  enabled: true
baltop:
  update: 2 # In minutes
webapi: # API for app
  enabled: false
  port: 8080
server_prefix: '&e&l[&6&lSYSTEM&e&l] &r'
halal_mode:
  enabled: false
  activate:
    pork: true
    day_food: true
  action: # Console commands
    - 'say &c&l%player% &chas %action%!'
    - 'soundall block.chain.fall 1 0.5'
    - 'lightning %player%'
database:
  host: 'localhost:3306'
  schema: 'canelones'
  username: '1234'
  password: '1234'
spawn:
  world: 'world'
  x: 0
  y: 0
  z: 0
  yaw: 0.0
  pitch: 0.0
first_join:
  commands:
    enabled: true
    execute:
      - 'lp user %player% parent add invitado'
      - 'kits-give %player% 4'
homes:
  max_homes: 4