tablist:
  enabled: true
  update: 1
  header:
    - '&cHEADER'
  footer:
    - '&cFOOTER'
messages:
  join:
    enabled: true
    message: '&e%prefix%%player%%suffix% &ejoined the game'
  leave:
    enabled: true
    message: '&e%prefix%%player%%suffix% &eleft the game'
  chat:
    enabled: true
    message: '&e%prefix%%player%%suffix%&r: %message%'
pm_tcom:
  enabled: true
baltop:
  update: 2 # In minutes
webapi: # API for app
  enabled: false
  port: 8080
server_prefix: '&e&l[&6&lSYSTEM&e&l] &r'
halal_mode:
  enabled: false
  activate:
    pork: true
    day_food: true
  action: # Console commands
    - 'say &c&l%player% &chas %action%!'
    - 'soundall block.chain.fall 1 0.5'
    - 'lightning %player%'