name: CanelonesCore
version: 2.1.2
main: me.pk2.canalosaland.CanelonesCore
author: PK2_Stimpy
description: CanelonesCore
api-version: 1.16
softdepend: [PlaceholderAPI, LuckPerms, Telecom, Vault, ProtocolLib, AuthMe]
commands:
  canelones-reload:
    description: Reloads the plugin
    usage: /<command>
  pm:
    description: Private message
    usage: /<command> <player> <message>
  msg:
    description: Private message
    usage: /<command> <player> <message>
  tell:
    description: Private message
    usage: /<command> <player> <message>
  r:
    description: Reply to a private message
    usage: /<command> <message>
  iphone:
    description: Open the iPhone menu
    usage: /<command>
  atm-manage:
    description: Manage the ATMs
    usage: /<command>
  baltop:
    description: See the richest players
    usage: /<command>
  say:
    description: Global server message
    usage: /<command> <message>
  soundall:
    description: Play a sound to all players
    usage: /<command> <sound> [volume] [pitch]
  halal:
    description: Halal mode
    usage: /<command> [on/off]
  lightning:
    description: Strike a player with lightning
    usage: /<command> <player>
  bounty:
    description: Set a bounty on a player
    usage: /<command> <player> <amount>
  interface:
    description: Open a interface
    usage: /<command> <interface>
  kits:
    description: Open the kit viewer menu
    usage: /<command>
  kits-remove:
    description: Remove a kit
    usage: /<command> <id>
  kits-create:
    description: Create a kit
    usage: /<command> <name>
  kits-give:
    description: Give a kit to a player
    usage: /<command> <player> <kit_id> [amount]
  kits-modify:
    description: Modify a kit
    usage: /<command> <kit_id>
  spawn:
    description: Teleport to spawn
    usage: /<command>
  spawn-set:
    description: Set the spawn
    usage: /<command>
  rename:
    description: Rename an item
    usage: /<command> <name>
  home:
    description: Teleport to a home
    usage: /<command> [home]
  sethome:
    description: Set a home
    usage: /<command> <home>
  delhome:
    description: Delete a home
    usage: /<command> <home>
  lang:
    description: Change your language
    usage: /<command>
  tpa:
    description: Send a tpa request to someone
    usage: /<command> <player>
  tpaccept:
    description: Accepts a teleport request
    usage: /<command>
  tpdeny:
    description: Denies a teleport request
    usage: /<command>
  mb:
    description: MysteryBox management command
    usage: /<command>